#!/usr/bin/env python3
"""Regenerate the OGP/Twitter Card meta tags in index.html from the top
news article, so link previews on X/etc. (which don't run script.js)
show the latest reported article instead of static site copy.

Run this whenever data/news.json changes; wired into
.github/workflows/deploy.yml so it runs automatically before each deploy.
"""
import datetime
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NEWS_PATH = ROOT / "data" / "news.json"
INDEX_PATH = ROOT / "index.html"
SITE_URL = "https://djtobby.github.io/toho-beads-news/"
DEFAULT_IMAGE = SITE_URL + "images/icons/icon-512.png"
SITE_NAME = "トーホービーズ ワールドニュース"
DEFAULT_DESCRIPTION = "世界中のトーホービーズ関連ニュースを集めて日本語で要約"

START_MARKER = "<!-- OGP:START (auto-generated by scripts/generate_ogp.py — do not hand-edit) -->"
END_MARKER = "<!-- OGP:END -->"


def top_article(articles):
    today = datetime.date.today().isoformat()
    reported = [a for a in articles if a.get("date", "") <= today]
    if not reported:
        return None
    reported.sort(key=lambda a: a["date"], reverse=True)
    return reported[0]


def truncate(text, limit):
    text = text.strip()
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def build_block(article):
    if article:
        title = f"{article['title']} | {SITE_NAME}"
        description = truncate(article["summary"], 140)
    else:
        title = SITE_NAME
        description = DEFAULT_DESCRIPTION

    title_esc = html.escape(title, quote=True)
    desc_esc = html.escape(description, quote=True)

    lines = [
        START_MARKER,
        '<meta property="og:type" content="website">',
        f'<meta property="og:site_name" content="{html.escape(SITE_NAME, quote=True)}">',
        f'<meta property="og:url" content="{SITE_URL}">',
        f'<meta property="og:title" content="{title_esc}">',
        f'<meta property="og:description" content="{desc_esc}">',
        f'<meta property="og:image" content="{DEFAULT_IMAGE}">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{title_esc}">',
        f'<meta name="twitter:description" content="{desc_esc}">',
        f'<meta name="twitter:image" content="{DEFAULT_IMAGE}">',
        END_MARKER,
    ]
    return "\n".join(lines)


def main():
    data = json.loads(NEWS_PATH.read_text(encoding="utf-8"))
    article = top_article(data.get("articles", []))
    new_block = build_block(article)

    html_text = INDEX_PATH.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL
    )
    if not pattern.search(html_text):
        print("FAIL: OGP markers not found in index.html")
        return 1

    updated = pattern.sub(new_block.replace("\\", "\\\\"), html_text, count=1)
    if updated != html_text:
        INDEX_PATH.write_text(updated, encoding="utf-8")
        print(f"Updated OGP tags for: {article['title'] if article else '(default)'}")
    else:
        print("OGP tags already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
